django-ogochukwubahscrumy/ogochukwubahscrumy/urls.py
from django.urls import path
from . import views
app_name = 'ogochukwubahscrumy'
urlpatterns =[
    path('', views.get_grading_parameters, name='get_grading_parameters')
]

myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ogochukwubahscrumy/', include('ogochukwubahscrumy.urls')),
    path('websocket/', include('websocket.urls')),
]

ogochukwubahscrumy/urls.py
from django.urls import path, include

from . import views

app_name = 'ogochukwubahscrumy'
urlpatterns = [
    path('', views.index, name='index'),
    path('movegoal/<int:goal_id>/', views.move_goal, name="move_goal"),
    path('addgoal/', views.add_goal, name="add_goal"),
    path('home/', views.home, name="home"),
    path('accounts/', include('django.contrib.auth.urls')),
]

django-ogochukwubahscrumy/ogochukwubahscrumy/models.py
from django.db import models

# Create your models here.

ogochukwubahscrumy/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class GoalStatus(models.Model):
    status_name = models.CharField(max_length=250)

    def __str__(self):
        return self.status_name


class ScrumyGoals(models.Model):
    goal_name = models.CharField(max_length=250)
    goal_id = models.IntegerField(default=1)
    created_by = models.CharField(max_length=250)
    moved_by = models.CharField(max_length=250, default=str)
    owner = models.CharField(max_length=250)
    goal_status = models.ForeignKey(GoalStatus, on_delete=models.PROTECT)
    user = models.ForeignKey(User, related_name='goal_created', on_delete=models.PROTECT)

    def __str__(self):
        return self.goal_name


class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=250)
    created_by = models.CharField(max_length=250)
    moved_from = models.CharField(max_length=250)
    moved_to = models.CharField(max_length=250)
    time_of_action = models.DateTimeField(default=timezone.now)
    goal = models.ForeignKey(ScrumyGoals, on_delete=models.CASCADE)

    def __str__(self):
        return self.created_by

# Create your models here.

ogochukwubahscrumy/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm, PasswordInput

from .models import ScrumyGoals


class SignupForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password', ]
        widgets = {
            'password': PasswordInput(),
        }


class CreateGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'user']


class MoveGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_status', ]

django-ogochukwubahscrumy/ogochukwubahscrumy/views.py
from django.shortcuts import render
from django.http import HttpResponse

def get_grading_parameters(request):
    return HttpResponse("Welcome to Django")

# Create your views here.

ogochukwubahscrumy/views.py
import random

from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render

from .forms import SignupForm, CreateGoalForm, MoveGoalForm
from .models import GoalStatus
from .models import ScrumyGoals

users_developer = Group.objects.get(name='Developer').user_set.all()
users_quality_assurance = Group.objects.get(name='Quality Assurance').user_set.all()
users_owner = Group.objects.get(name='Owner').user_set.all()
users_admin = Group.objects.get(name='Admin').user_set.all()

weekly_goal = GoalStatus.objects.get(status_name='Weekly Goal')
done_goal = GoalStatus.objects.get(status_name='Done Goal')
verify_goal = GoalStatus.objects.get(status_name='Verify Goal')
daily_goal = GoalStatus.objects.get(status_name='Daily Goal')


def index(request):
    form = SignupForm()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            new_user.set_password(request.POST.get('password'))
            my_group = Group.objects.get(name='Developer')
            my_group.user_set.add(new_user)
            new_user.save()
            return HttpResponse("Your account has been created successfully")
    else:
        form = SignupForm()
    return render(request, 'ogochukwubahscrumy/index.html', {'form': form})


def home(request):
    context = {
        'Users': User.objects.all(),
        'WeeklyGoal': weekly_goal.scrumygoals_set.all(),
        'DailyGoal': daily_goal.scrumygoals_set.all(),
        'VerifyGoal': verify_goal.scrumygoals_set.all(),
        'DoneGoal': done_goal.scrumygoals_set.all(),
        'scrumy_goal': ScrumyGoals.objects.all()
    }
    return render(request, 'ogochukwubahscrumy/home.html', context)


def add_goal(request):
    number = random.randint(1000, 10000)
    goal_id_list = []
    if number not in goal_id_list:
        id = number
        goal_id_list.append(number)

    current_user = request.user

    if request.method == 'POST':
        form = CreateGoalForm(request.POST)
        if form.is_valid():
            if current_user in users_developer:
                if current_user != form.cleaned_data.get('user'):
                    return HttpResponse(
                        f"You are not authorised to create a new goal for {form.cleaned_data.get('user')}")
                else:
                    new_goal = form.save(commit=False)
                    new_goal.goal_id = id
                    new_goal.goal_status = weekly_goal
                    new_goal.user = current_user
                    new_goal.save()
                    return HttpResponse("You have successfully created a new goal")

            elif current_user in users_quality_assurance:
                if current_user != form.cleaned_data.get('user'):
                    return HttpResponse(
                        f"You are not authorised to create a new goal for {form.cleaned_data.get('user')}")
                else:
                    new_goal = form.save(commit=False)
                    new_goal.goal_id = id
                    new_goal.goal_status = weekly_goal
                    new_goal.user = current_user
                    new_goal.save()
                    return HttpResponse("You have successfully created a new goal")

            elif current_user in users_owner:
                new_goal = form.save(commit=False)
                new_goal.goal_id = id
                new_goal.goal_status = weekly_goal
                new_goal.user = form.cleaned_data.get('user')
                new_goal.save()
                return HttpResponse("You have successfully created a new goal")
    else:
        form = CreateGoalForm()
    return render(request, 'ogochukwubahscrumy/addgoal.html', {'form': form})


def move_goal(request, goal_id):
    try:
        goal = ScrumyGoals.objects.get(goal_id=goal_id)
        form = MoveGoalForm()
        current_user = request.user

        if request.method == 'POST':
            form = MoveGoalForm(request.POST)
            if form.is_valid():
                if current_user in users_developer:
                    if goal.user != current_user:
                        return HttpResponse(f"You are not authorised to move {goal.user}'s goals")
                    goal.goal_name = goal.goal_name
                    if form.cleaned_data.get('goal_status') == done_goal:
                        return HttpResponse(f"You are not authorised to move {goal.goal_name} to"
                                            f" {form.cleaned_data.get('goal_status')}")
                    else:
                        goal.goal_status = form.cleaned_data.get('goal_status')
                        goal.save()
                        return HttpResponse(f"You have successfully moved {goal.goal_name} to {goal.goal_status}")

                elif current_user in users_quality_assurance:
                    goal.goal_name = goal.goal_name

                    if goal.user == current_user:
                        goal.goal_status = form.cleaned_data.get('goal_status')
                        goal.save()
                        return HttpResponse(f"You have successfully moved {goal.goal_name} to {goal.goal_status}")

                    elif goal.user != current_user:
                        if goal.goal_status == verify_goal:
                            if form.cleaned_data.get('goal_status') != done_goal:
                                return HttpResponse(
                                    f"You are not authorised to move {goal.goal_status} to"
                                    f" {form.cleaned_data.get('goal_status')}")
                            else:
                                goal.goal_status = form.cleaned_data.get('goal_status')
                                goal.save()
                            return HttpResponse(f"You have successfully moved {goal.goal_name} to {goal.goal_status}")
                        else:
                            return HttpResponse(f"You are not authorised to move {goal.goal_name} to {goal.goal_status}")

                elif current_user in users_admin:
                    goal.goal_name = goal.goal_name
                    goal.user = goal.user
                    goal.goal_status = form.cleaned_data.get('goal_status')
                    goal.save()
                    return HttpResponse(f"You have successfully moved {goal.goal_name} to {goal.goal_status}")

                elif current_user in users_owner:
                    goal.goal_name = goal.goal_name
                    if goal.user == current_user:
                        goal.goal_status = form.cleaned_data.get('goal_status')
                        goal.save()
                        return HttpResponse(f"You have successfully moved {goal.goal_name} to {goal.goal_status}")
                    else:
                        return HttpResponse(f"You are not authorised to move {goal.user}'s goals")
            else:
                form = MoveGoalForm()

    except ScrumyGoals.DoesNotExist:
        return render(request, 'ogochukwubahscrumy/exception.html',
                      {'error': 'A record with that goal id does not exist'})

    return render(request, 'ogochukwubahscrumy/movegoal.html', {'form': form})

# Create your views here.

ogochukwubahscrumy/templates/ogochukwubahscrumy/addgoal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add a New Goal</title>
 <p>Currently logged in as:<strong>{{ request.user }}</strong></p>
</head>
<body>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add New Goal">
</form>

<a href="{% url 'ogochukwubahscrumy:home' %}">Go to Homepage</a>
</body>
</html>

ogochukwubahscrumy/templates/ogochukwubahscrumy/exception.html
<p>A record with that goal id does not exist</p>

ogochukwubahscrumy/templates/ogochukwubahscrumy/home.html
<!DOCTYPE html>
<html>
<title>Homepage</title>

<head>
    <style>
        table, th, td {
            border: 2px solid black;
            border-collapse: collapse;
            margin: 75px;
        }

        th, td {
            padding: 5px;
            text-align: center;
        }
    </style>
    <p>Currently logged in as:<strong>{{ request.user }}</strong></p>
    <div class="top-right">
        <a href="{% url 'ogochukwubahscrumy:add_goal' %}">Add a new goal</a>
    </div>
</head>
<body>
<table style="width:70%">
    <caption><strong>SCRUMY BOARD</strong></caption>
    <tr>
        <th>User</th>
        <th>Weekly Goals</th>
        <th>Daily Goals</th>
        <th>Verify Goals</th>
        <th>Done Goals</th>
    </tr>

    {% for user in Users %}
        <tr>
            <td>{{ user }}</td>
            <td>
                {% for goal in user.goal_created.all %}
                    {% if goal in WeeklyGoal %}
                        {{ goal.goal_name }}, {{ goal.goal_id }}<br>
                        <a href="{% url 'ogochukwubahscrumy:move_goal' goal.goal_id %}">Move This Goal</a>
                        <br><br>
                    {% endif %}
                {% endfor %}
            </td>
            <td>
                {% for goal in user.goal_created.all %}
                    {% if goal in DailyGoal %}
                        {{ goal.goal_name }}, {{ goal.goal_id }}<br>
                        <a href="{% url 'ogochukwubahscrumy:move_goal' goal.goal_id %}">Move This Goal</a>
                        <br><br>
                    {% endif %}
                {% endfor %}
            </td>
            <td>
                {% for goal in user.goal_created.all %}
                    {% if goal in VerifyGoal %}
                        {{ goal.goal_name }}, {{ goal.goal_id }}<br>
                        <a href="{% url 'ogochukwubahscrumy:move_goal' goal.goal_id %}">Move This Goal</a>
                        <br><br>
                    {% endif %}
                {% endfor %}
            </td>
            <td>
                {% for goal in user.goal_created.all %}
                    {% if goal in DoneGoal %}
                        {{ goal.goal_name }}, {{ goal.goal_id }}<br>
                        <a href="{% url 'ogochukwubahscrumy:move_goal' goal.goal_id %}">Move This Goal</a>
                        <br><br>
                    {% endif %}
                {% endfor %}
            </td>
        </tr>

    {% endfor %}

</table>
</body>
</html>

ogochukwubahscrumy/templates/ogochukwubahscrumy/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SignUp</title>
</head>
<body>
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign Up">
    </form>
</div>
</body>
</html>

ogochukwubahscrumy/templates/ogochukwubahscrumy/movegoal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Move Goal</title>
    <p>Currently logged in as:<strong>{{ request.user }}</strong></p>
</head>
<body>
<form method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Move Goal">
</form>
</body>
</html>